Repository joaoderocha/JCL-OptSolver, pull requests merged in 2020-05, with the labels that each got.

#28 fix(readme): adiciona hifen
  README.md
Labels: bug

#30 feat(kernel): Renomeia JCLglobalVariablesAccess para JCLdataAccess e move para kernel.utils
  src/main/java/kernel/utils/JCLdataAccess.java
Labels: feat

#31 feat: inclui interface do search strategy
  src/main/java/kernel/search_strategy/SearchStrategy.java
Labels: feat

#32 Refactor migrating to maven
  .github/workflows/maven.yml
  .gitignore
  .settings/org.eclipse.buildship.core.prefs
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.jdt.ui.prefs
  .settings/org.sonarlint.eclipse.core.prefs
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  pom.xml
  settings.gradle
Labels: enhancement

#33 fix: workspace
  WORKSPACE.md
Labels: enhancement

#34 fix: removed duplicated classes
  src/main/java/kernel/user_commands/LoadAbstract.java
  src/main/java/kernel/utils/JcldataAccess.java
  src/main/java/kernel/utils/Operations.java
  src/main/java/kernel/utils/Pair.java
  src/main/java/utils/Operations.java
  src/main/java/utils/TrotterJhonson.java
  src/test/java/kernel/utils/PairTest.java
Labels: enhancement

#35 test(kernel-utils): refatora TrotterJhonson e inclui testes correspondentes
  src/main/java/kernel/utils/TrotterJhonson.java
  src/test/java/kernel/utils/TrotterJhonsonTest.java
Labels: enhancement

#36 feat(kernel.exception): adiciona JCLoptException e seus respectivos testes
  src/main/java/kernel/exception/JCLoptException.java
  src/test/java/kernel/exception/JCLoptExceptionTest.java
Labels: feat

#39 feat(kernel.utils): inclui interface JclOptObject e as classes JclOptSingleton e JclOptNonSingleton
  src/main/java/kernel/utils/JclOptNonSingleton.java
  src/main/java/kernel/utils/JclOptObject.java
  src/main/java/kernel/utils/JclOptSingleton.java
Labels: feat

#41 feat: inclui workflow novo e deploy info no projeto
  .github/workflows/deploy.yml
  .github/workflows/development.yml
  pom.xml
Labels: enhancement, feat

#43 feat: inclui abstracao JclOptNonSingleton
  src/main/java/common/JclOptNonSingleton.java
  src/main/java/common/JclOptObject.java
  src/main/java/common/JclOptSingleton.java
  src/main/java/kernel/utils/JclOptNonSingleton.java
  src/main/java/kernel/utils/JclOptObject.java
  src/main/java/kernel/utils/JclOptSingleton.java
  src/test/java/kernel/common/JclOptNonSingletonTest.java
Labels: enhancement

#44 feat: inclui implementação do LoadAbstract no contexto da aplicacao
  pom.xml
  src/main/java/implementation/user_commands/CoordinatesXY.java
  src/main/java/implementation/user_commands/DistanceMatrix.java
  src/main/java/kernel/utils/JcldataAccess.java
Labels: enhancement, feat
